frame_files <- lapply(sys.frames(), function(x) x$ofile)
frame_files <- Filter(Negate(is.null), frame_files)
PATH <- dirname(frame_files[[length(frame_files)]])
img <- readPNG(paste(PATH,"Q.png",sep="/"))
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE)
rasterImage(img,0,-0.3,1,1)
